name: tdigest
version: "0"
synopsis: On-line accumulation of rank-based statistics such as quantiles and trimmed means
description: |
  A new data structure for accurate on-line accumulation of rank-based statistics such as quantiles and trimmed means.

  See original paper: "Computing extremely accurate quantiles using t-digest" by Ted Dunning and Otmar Ertl
  for more details <https://github.com/tdunning/t-digest/blob/master/docs/t-digest-paper/histo.pdf>.

author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-tdigest
category: Numeric
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base                >=4.7      && <4.10
- base-compat         >=0.9.1    && <0.10
- deepseq             >=1.3.0.2  && <1.5
- binary              >=0.7.1.0  && <0.9
- semigroups          >=0.18.2   && <0.19
- vector              >=0.11     && <0.12
- vector-algorithms   >=0.7.0.1  && <0.8

library:
  source-dirs: src

tests:
  tdigest-tests:
    source-dirs: tests
    main: Tests.hs
    dependencies:
      - base
      - tdigest
      - tasty            >=0.11.0.4 && <0.12
      - tasty-quickcheck >=0.8.4    && <0.9

benchmarks:
  tdigest-simple:
    source-dirs: bench
    main: Simple.hs
    ghc-options: -threaded
    dependencies:
      - tdigest
      - machines             >=0.6.1    && <0.7
      - parallel             >=3.2.1.0  && <3.3
      - mwc-random           >=0.13.4.0 && <0.14
      - statistics           >=0.13.3.0 && <0.14
      - time                 >=1.6.0.1  && <1.7
      - optparse-applicative >=0.12.1.0 && <0.14
